name: Tests
on:
  push:
    branches: [ main ]

jobs:
  test_linux_headless:
    name: UI tests (Ubuntu + Monocle)
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages for JavaFX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev libavcodec-dev libavformat-dev libavutil-dev \
            libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk+fx'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven
      - name: Run tests (headless with Monocle)
        run: ./mvnw -B -Pheadless-ci -DskipNative=true test
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*
            **/target/failsafe-reports/*